### ISSUE TITLE
UUID not found for licdn.com

### ISSUE THREAD

**Issue by kbsali** [uploadcare/uploadcare-php#100]
Hi,

we are having issue when trying to upload linkedin image like :
https://media.licdn.com/mpr/mprx/0_035CG7R8of23xiBUdkZTQc9iEAuHoTMjRFZ5BlBQoGTDoSsgZFZTQzELVf3Do7c-srM3KVI8d68DHKRtfEqDzNwQY68SHKwOYEq887B6IpAkHFVBYaXTogmza-

This throws an `UUID not found` exception. The regex does not have tests, so it's hard to understand what it does/should do.

Any hints?
Thanks

**Comment by dmitry-mukhin** [comment]
Show us the code you're using, now it's out of context.

**Comment by kbsali** [comment]
Hard to give a lot of context, but basically here is where we call uploadcare : 
```php
...
    public function upload(Image $image)
    {
        try {
            $file = $this->uploadCareClient->getFile($image->getUrl());
            $originalFile = $this->uploadCareClient->getFile($file->getUuid());
        } catch (Exception $e) {
            $this->logger->warning(sprintf('Problem uploading image url %s', $image->getUrl()));
            throw $e;
        }
        ...

        return $image;
    }
...
```

**Comment by dmitry-mukhin** [comment]
`Api->getFile` should be used to get already uploaded file, providing a UUID or CDN URL (in Uploadcare CDN). It does not upload a file.

You should use
`Uploader->fromUrl` method to upload a file from arbitrary URL
