### ISSUE TITLE
Get 404 error when get group files

### ISSUE THREAD

**Issue by apvpn** [uploadcare/uploadcare-php#114]
Hello Team,
When I try to get group files then it will give me below screenshot mention error.
http://prntscr.com/n4zozq
could you please give me solution for it?

**Comment by dmitry-mukhin** [comment]
@apvpn 
please provide steps to reproduce this and|or your code

**Comment by apvpn** [comment]
> @apvpn
> please provide steps to reproduce this and|or your code

I have using below steps to integrate uploadcare in my slim php framework Project.

1)  Install uploadcare dependency using composer
     -> Update composer.php file
           "require": {
                    "uploadcare/uploadcare-php": ">=v2.0,<3.0"
             }
     -> and run : composer update --no-dev
2) Now Create form to use with widget:
	$api = new Uploadcare\Api('UC_PUBLIC_KEY', 'UC_SECRET_KEY');
    return $view->render($response, 'userGallery.twig', [
        'inputTag' => $api->widget->getInputTag('qs-file', array("data-images-only" => "true" ,"data-multiple"=>"true"))
    ]);

    In userGallery.twig file
    <form id="postGalleryImage" action="/userpanel/gallery/postImage" method="post" enctype="multipart/form-data" data-ajax="false">
          {{ csrf.field | raw }}
          <div class="form-inline">
            <div class="uploader-black-button">
              {{ inputTag | raw}}
            </div>
            <hr/>
            <button type="submit" class="btn btn-block btn-primary">Upload file</button>
          </div>
    </form>
3) Now get group images using below logiv then get 404 error

	-> 	$api = new Uploadcare\Api('UC_PUBLIC_KEY', 'UC_SECRET_KEY');
    	$file_id = $request->getParams();
    	$group = $api->getGroup($file_id['qs-file']);
    	$files = $group->getFiles();
Error message screenshot : https://prnt.sc/n4zozq

Could you please help me to solve this issue?

**Comment by dmitry-mukhin** [comment]
does cURL command with the same API KEYs and Group UUID give result other than 404?
I.e. are you sure that the group exists in your project?

**Comment by dmitry-mukhin** [comment]
@apvpn would you mind to elaborate? did you find the route cause?
