### ISSUE TITLE
Library doesn't support additional upload parameters

### ISSUE THREAD

**Issue by sigismund** [uploadcare/uploadcare-php#127]
API reference for upload via [from_url](https://uploadcare.com/docs/api_reference/upload/from_url/) mentions parameters:
* save_URL_duplicates
* check_URL_duplicates

These 2 API parameters are newer included in requests. Maybe it would be a good idea to future proof library by merging all options, passed to `fromUrl` as second parameter, with `$requestData` used by Curl.

**Comment by dmitry-mukhin** [comment]
Sure, PRs are welcome :)
