### ISSUE TITLE
Simple authorization

### ISSUE THREAD

**Issue by rsedykh** [uploadcare/uploadcare-php#130]
https://uploadcare.com/api-refs/rest-api/v0.6.0/#section/Authentication

(https://uploadcare.com/docs/rest_api/requests_auth/#auth-simple)

**Comment by andrew72ru** [comment]
Why we should implement weak auth when we already have the strong one (see #140 and #145) which works in automatic mode? I propose to close this issue without implementation.
@rsedykh
