### ISSUE TITLE
Pagination, filtering and sorting for Files and Groups (REST API)

### ISSUE THREAD

**Issue by rsedykh** [uploadcare/uploadcare-php#134]

**Comment by andrew72ru** [comment]
Right now we can:
- request list of files, ordered by any field and filtered by stored and removed states and get the answer;
- request next page for this answer;
- request list of groups **without** any filters and with sort only by `datetime_created` ASC / DESC;
- and request next page for list of groups

The main API does not allows any other opportunities, I think, this issue can be closed.
