### ISSUE TITLE
Bootstrap new project for v3

### ISSUE THREAD

**Issue by rsedykh** [uploadcare/uploadcare-php#139]
Add user-agent that lib sends to us to identify itself.

Closes https://github.com/uploadcare/uploadcare-php/issues/26?

**Comment by andrew72ru** [comment]
The right way described [here](http://docs.php-http.org/en/latest/message/message-factory.html).

Unfortunately, PSR-17 http-message interfaces requires php >= 7.0, and we cannot use it. We can use PSR-7, but MessageFactoryDiscovery class is deprecated in php-http package and will be removed in 2.0 version.

There is two ways: use concrete `guzzlehttp/psr7` package and drop all abstractions above http-client or use deprecated MessageFactoryDiscovery from `php-http/message` v 1.0 and freeze it in this version.
