### ISSUE TITLE
Authenticated URLs

### ISSUE THREAD

**Issue by rsedykh** [uploadcare/uploadcare-php#146]
https://uploadcare.com/docs/security/secure_delivery/

See #124.

**Comment by andrew72ru** [comment]
The proposal is:

- Add abstract generator class with methods `getTimeStamp`, `getToken`
- Add `SecureDelivery` class, which will gets this abstract class and CDN identification (akimai / key);
- Add method to `Uploadcare\Configuration` class, which gets this `SecureDelivery` class;
- Add `makeSecureUrl` method to `FileApi`, which will make a url by template, if configuration has a `SecureDelivery` property is not null.

In this way, we offer to library user to make concrete generator class, make `SecureDelivery` class with this generator and set this class to the `Configuration` property. Thus, if library user does all this things, he can get a secure url from `FileApi` (and Active File, accordingly).
