### ISSUE TITLE
Add a `$custom_headers` parameter to `createRemoteCopy`

### ISSUE THREAD

**Issue by kbsali** [uploadcare/uploadcare-php#168]
Hi,

We would like to update some metadata to the object copied to our S3 Bucket, and because `createRemoteCopy` does not allow such thing, we need to do it calling `Aws\S3\S3Client::copyObject()` after the copy is done.
It would save us 2 extra S3 calls
- 1 to retrieve the existing metadata,
- 2) to update the metadata to our needs
This means more time to process a file upload (and somehow money too).

Our specific need today is being able to set the `max-age` to 1 year (`'CacheControl' => 'public, max-age=XXX'`)

Thanks

**Comment by rsedykh** [comment]
Hi @kbsali. Sorry for taking so long.. That is not an issue with PHP client, that's how Uploadcare API works (see https://uploadcare.com/api-refs/rest-api/v0.6.0/#operation/copyFileLocal).

I've filed a feature request concerning your issue.
