### ISSUE TITLE
Missing URL on File in FileCollection when fetching it from group

### ISSUE THREAD

**Issue by calcifer1337** [uploadcare/uploadcare-php#184]
### Describe the bug

When I fetch Files from a FileCollection i fetched from a Group there is no CDN URL set.

### Expected behavior

The File should have a CDN URL

### Code / screenshots
`$group->getFiles()->first()`

![Bildschirmfoto 2021-10-22 um 17 37 28](https://user-images.githubusercontent.com/43297005/138483377-83a051e3-a227-4ab1-84c1-dbcc3cc73d5b.png)

### Environment

 - Library version: 3.1.1
 - Language/framework version: PHP 8.0
 - OS version: Mac OS

**Comment by rsedykh** [comment]
Hi. Fixed in https://github.com/uploadcare/uploadcare-php/commit/571da09a8af4d470f2631b196b6216befee17468.
