### ISSUE TITLE
Secure Delivery File Transformations Not Working

### ISSUE THREAD

**Issue by AlexJezior** [uploadcare/uploadcare-php#186]
### Describe the bug

Following the documentation found [here](https://github.com/uploadcare/uploadcare-php#secure-delivery-for-transformed-images) for image transformations.

When providing a transformation, the URL generated gives a 403 error. 

To reproduce, the following is being used: `$api->file()->generateSecureUrl('/'.$img->uuid.'/-/preview/150x150/-/enhance/25/-/sharp/');`

When viewing the output URL, you can observe extra forward slashes being used in the URL:
`https://cdn.mysite.com//{UUID}/-/preview/150x150/-/enhance/25/-/sharp//?token=exp={TIMESTAMP}~acl=//{UUID}/-/preview/150x150/-/enhance/25/-/sharp//~hmac={TOKEN}`

This also results in a 403 error with the extra sashes(/):
`$api->file()->generateSecureUrl('/'.$img->uuid.'/');`

This returns successful:
`$api->file()->generateSecureUrl("$img->uuid");`

### Expected behavior
Expect transformations to work per documentation example:
`$api->file()->generateSecureUrl('/{uuid}/-/resize/640x/other/transformations/');`

### Code / screenshots

Examples provided in description above.

### Environment

 - Library version: 3.1.1
 - Language/framework version: PHP 7.4 / Laravel 8.61.0
 - OS version: Debian 10 buster

**Comment by rsedykh** [comment]
Thank you Alex for your PR! Update is released — https://github.com/uploadcare/uploadcare-php/releases/tag/v3.2.1.

**Comment by AlexJezior** [comment]
Thanks for merging this promptly! 

However, I noticed the `3.2.1` tag does not include this fix

**Comment by rsedykh** [comment]
Oops. Created tag from a wrong branch. I've just published a new release — https://github.com/uploadcare/uploadcare-php/releases/tag/v3.2.1. Now should be latest and greatest!

**Comment by AlexJezior** [comment]
Thank you!!!
