### ISSUE TITLE
Access to the raw json response

### ISSUE THREAD

**Issue by rhpaiva** [uploadcare/uploadcare-php#188]
### Question

Hi guys. Is it possible to have access to the raw response instead of having to navigate through the OOP model?
Or is there a way to convert the FileInfoInterface into an array with your library? I need to save the file data as json.

Thanks

**Comment by rsedykh** [comment]
Hi.

To do this, you should use API directly:
- http://uploadcare.com/api-refs/rest-api/v0.6.0/
- http://uploadcare.com/api-refs/upload-api/

Or you can serialize this object in any way you want. But current library doesn't have a tool for that.

**Comment by rhpaiva** [comment]
I see. Thanks for the answer!
