### ISSUE TITLE
Question: How do I get the original Image Dimensions

### ISSUE THREAD

**Issue by yahya-uddin** [uploadcare/uploadcare-php#193]
### Question

Given a URL e.g, `https://ucarecdn.com/<uuid>/-/preview/30x50/`
how can I get the original width and height.

Right now I can get the transformed dimensions as follows:

```
$file = $api->uploader()->fromUrl("https://ucarecdn.com/<uuid>/-/preview/30x50/");
// This gives the transformed dimensions
$width = $file->getImageInfo()->getWidth(); 
$height = $file->getImageInfo()->getHeight();
```

Environment is: PHP 8.1

**Comment by andrew72ru** [comment]
No way to do this in this case. Basically speaking, Uploader receives already transformed file so the original dimensions is 30x50. Call `fileInfo` from [File API](https://github.com/uploadcare/uploadcare-php#file-operations) to receive original file properties.
