### ISSUE TITLE
getOriginalFileUrl() sometimes returns empty string

### ISSUE THREAD

**Issue by kukicado** [uploadcare/uploadcare-php#197]
### Expected behavior

I have a Laravel Action that takes an image from the local filesystem and uploads it to uploadcare. I am using the `$uploader->fromPath()` method and capturing the response in a `$response` variable:

```
$response = $uploader->fromPath($filePath, 'image/png');
```

and then returning the original file url by doing `return $response->getOriginalFileUrl();`.

The issue that I run into is, sometimes the `$response->getOriginalFileUrl();` will return an empty string. The file still gets uploaded to uploadcare, I can access the $getUuuid() and $getOriginalFilename() methods just fine. I'm wondering if I'm doing something wrong or is there a way to wait until $response->getOriginalFileUrl() is populated?

### Environment

 - Library version: 3.2.4
 - Language/framework version: Laravel 9 / PHP 8.1
 - OS version: Ubuntu 22

**Comment by rsedykh** [comment]
Hi.

It's an issue with files created before introducing metadata. API bug that we'll be fixed soon.

**Comment by rsedykh** [comment]
Hi. `original_file_url` is publicly available if a file is not deleted (or not yet stored).

That's why `getOriginalFileUrl` returns you an empty string. Use `$response->isReady())` to check it's readiness before you can get an original file URL.
