### ISSUE TITLE
Deprecate PUT /group/{uuid}/storage/

### ISSUE THREAD

**Issue by rsedykh** [uploadcare/uploadcare-php#207]
It was deprecated.

<img width="868" alt="image" src="https://github.com/uploadcare/uploadcare-php/assets/515987/56a7534d-8b27-42c9-81a7-af10a92315f4">

https://uploadcare.com/api-refs/upload-api/#tag/Groups/operation/filesGroupInfo
https://uploadcare.com/api-refs/rest-api/v0.7.0/#tag/Group/operation/groupInfo

To store or remove files from a group, query the list of files in it, split the list into chunks of 100 files per chunk and then perform batch file storing or batch file removal for all the chunks.

p.s. Don't forget to update uploadcare-php-example if necessary.

**Comment by andrew72ru** [comment]
> To store or remove files from a group, query the list of files in it
Neither the PHP library nor Uploadcare API itself don't have such methods. Group operations are Create, Delete, Get, and List — we can't request the "List of files", "Add file to group", or "Remove file from the group".

When the deprecated property is removed, the PHP Library's property will be set to a `null` value. However, I've marked the `getDatetimeStored` method as deprecated on the library side as well.
