### ISSUE TITLE
use http requests lib

### ISSUE THREAD

**Issue by dmitry-mukhin** [uploadcare/uploadcare-php#26]
evaluate and try to use
- http://requests.ryanmccue.info/
- https://github.com/guzzle/guzzle

**Comment by bautrukevich** [comment]
I am recommend http://unirest.io/php.html — the more lightweight and good library

**Comment by dmitry-mukhin** [comment]
great, do that then :)

**Comment by rsedykh** [comment]
We use it in [3.0.0](https://github.com/uploadcare/uploadcare-php/releases/tag/3.0.0).
