### ISSUE TITLE
ThrottledRequestException won't be thrown

### ISSUE THREAD

**Issue by lexabug** [uploadcare/uploadcare-php#62]
ThrottledRequestException won't be throw since autoloader won't find the class file in the `src` folder. Also I'd recommend to please `ThrottledRequestException.php` into `src\Excpetions` folder and place `ThrottledRequestException` class into `Uploadcare\Exceptions` namespace. That would comply with PSR-4.

**Comment by dmitry-mukhin** [comment]
closed via #63
