### ISSUE TITLE
Качество изображения и другие функции CDN

### ISSUE THREAD

**Issue by jufy** [uploadcare/uploadcare-php#64]
Планируется ли реализовывать настройку качества изображения через библиотеку и других параметров CDN?

**Comment by dmitry-mukhin** [comment]
Can you give us an example of the desired usage?

**Comment by dmitry-mukhin** [comment]
There's a built in mechanism to use operations that are not (yet) covered by PHP API. E.g:
```php

$file->op('effect/flip')
```
