### ISSUE TITLE
Ability to extract Cropped Dimensions

### ISSUE THREAD

**Issue by MattWohler** [uploadcare/uploadcare-php#66]
Being able to get the cropped dimensions that the User selected (which would be in the URL or the "default_effects" private member) would be a huge feature.

Because the cropped image is not saved. I need a way to parse for this.

**Comment by dmitry-mukhin** [comment]
Matt,

take a look at #67.
Effects are being preserved in File instance if it's created from a Group.

**Comment by dmitry-mukhin** [comment]
@MattWohler ?

**Comment by MattWohler** [comment]
I don't see the benefit of accessing it via group over individual file, but it's your choice as to implement it or not.  In my use-case, the user creates their own cropped image and I need to preserve those cropped dimensions.

In this case, are we encouraged to use File Groups?

**Comment by dmitry-mukhin** [comment]
@MattWohler the individual files do not store the cropping info in any form, it is only available in groups.
You'll have to save the file URL returned by the widget to have the cropping info.

So the question to you is what you're actually putting into your DB when you save files?

**Comment by dmitry-mukhin** [comment]
resolved in #67

**Comment by MattWohler** [comment]
| id  | user_id | avatar_uuid  | avatar_crop_size |
| ------------- | ------------- | ------------- | ------------- |
| 1  |1  | b39ds8f39f-4387-4cc0-3118-bc49sh8984a7  | crop/239x239/145,24  |

Where my code ends up looking something like the following:

```php

        $fileUrl = $request->input('avatar');
        $file = $this->api->getFile($fileUrl);

        $startAt  = strpos($fileUrl, 'crop');
        $stopAt   = strpos($fileUrl, '/-/preview');
        $cropSize = substr($fileUrl, $startAt, ($stopAt - strlen($fileUrl)));

        $userProfile->avatar_uuid = $file->getFileId();
        $userProfile->avatar_crop_size = $cropSize;
```

**Comment by dmitry-mukhin** [comment]
Not sure if gihub is a good place for this :)

But anyway, if you instantiate File with full URL, returned by the widget, you get the cropping and your code successfully extracts it (take a look at $file->default_effects though).

 Uploadcare does not have this info (for individual files), and hence cannot give it to you via REST API.
