### ISSUE TITLE
Add an option to getScriptTag() to get the non-full version

### ISSUE THREAD

**Issue by weotch** [uploadcare/uploadcare-php#68]
Would be nice to use the `getScriptTag()` to build a script tag without jquery included.

**Comment by dmitry-mukhin** [comment]
that should be super easy, just include `uploadcare.min.js` instead of `uploadcare.full.min.js`
do you think you can prepare a PR?

**Comment by dmitry-mukhin** [comment]
done in cdbba2adfc6bafd95e6
